### ISSUE TITLE
Remove the overrideLocalConfig function definition

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode-subsites#17]
[This](https://github.com/geosolutions-it/geonode-subsites/blob/main/subsites/templates/geonode-mapstore-client/_geonode_config.html#L6-L15) is not needed, since we already set the `siteurl` inside the [override_settings](https://github.com/geosolutions-it/geonode-subsites/blob/main/subsites/templates/geonode-mapstore-client/_geonode_config.html#L17-L24) block, and it also overrides the `overrideLocalConfig`  that could be define by the hosting project.

**Comment by mattiagiupponi** [comment]
remove via https://github.com/geosolutions-it/geonode-subsites/pull/18 (github is not making the link between pr and issue)
