### ISSUE TITLE
subsite catalogue home is not aligned with subsite

### ISSUE THREAD

**Issue by mattiagiupponi** [geosolutions-it/geonode-subsites#19]
We have a scenario where `CATALOG_HOME_REDIRECTS_TO` is not set.
This means that the subsite can have bot home page and catalogue page.
The catalogue page works as expected and the subsite is mantained.
From the home page, if i click on "Filter" from the subsite page, the page is redirected to the root website page
Example:
![facets](https://github.com/geosolutions-it/geonode-subsites/assets/51856725/29a96110-a336-4087-aae2-862852eeddc2)

This is happening because the client use an hard-coded catalogue URL.
I suggest to add in the `_geonode_config.html`  the possibility to define the catalogue URL (like we do the with the siteUrl) or the client should use that as a value for the catalogue.

@dsuren1 @giohappy

**Comment by dsuren1** [comment]
> This is happening because the client use an hard-coded catalogue URL.

As of now, this path is configurable but only as [plugin configuration](https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx#L144) using the `cfg.filterPagePath`.

**Comment by dsuren1** [comment]
#### Change required on client side
- Update templates where catalogue path is pre-configured
- Update `ResourceGrid` plugin configurations to support `CATALOG_PAGE_PATH` and menu items link
- Update redirection urls wherever applicable (i.e epics and in components)

**Comment by dsuren1** [comment]
Upstream [issue](https://github.com/GeoNode/geonode-mapstore-client/issues/1596) client

**Comment by mattiagiupponi** [comment]
config merged in subsite, now it works as expected
