### ISSUE TITLE
Implement templates per subiste

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode-subsites#2]
We want to be able to customize templates per subsite (geonode_config, home, snippets, etc.).
Since subsites are data models, we don't have a real folder per subsite. My proposal is to make the module look for a folder named `subsite.slug` under the `subsites/templates/` folder and use it as the root of the subsite's templates.

For example for website "site_1" its home template will be picked from `subsites/templates/site_1/home.html` if it exists. Otherwise the normal template lookup will be used.

**Comment by giohappy** [comment]
@mattiagiupponi if I understand it correctly the following subtree will be under the subsites module:

```
➜  templates git:(ISSUE_2) ✗ tree ../templates 
../templates
├── geonode-mapstore-client
│   ├── _geonode_config.html
│   └── snippets
│       ├── brand_navbar.html
│       ├── search_bar.html
│       └── topbar.html
└── subsite_1
    └── _geonode_config.html
```

and we must implement a template file under subsites/templates/  for every template we want to be able to override per subsit e, correct?

Well, it's not that great from the developer's point of view, since if I want to override a snippet not included in the geonode-subsites module I cannot do it unless I extend geonode-subsites.

Isn't there a way to hijack the template rendering inside the views, rather than using template conditionals?

**Comment by mattiagiupponi** [comment]
I was trying to avoid the override of too many URLs, but yes this could be another option.
I'll try to make a test on my local env to test it out

**Comment by mattiagiupponi** [comment]
@giohappy follows a second idea about how to handle the subsite template.
In few words a new TemplateEngine and a CustomLoader is available in the subsite app.
This still needs some work but should give you an overall idea.

In this way the bakcend will dynamically load the template (if exists) based on the subapp that is called.

The PR in draft is here: https://github.com/geosolutions-it/geonode-subsites/pull/3

**Comment by mattiagiupponi** [comment]
Hi @giohappy 
I just update the proposal about this issue.
In the end we debug together the issue, but better to give a quick sum-up.

The approach we decided is the following as first implementation:
- create a new render function that is going to be used for the subsite only
- the render function will intiiate from scratch a new instance of the DjangoTemplates engine with its parameter
- We inject dinamically (based on the subsite) the path that contains the template for the specific subsite that the user is asking for
- The default DjangoTemplate engine will take care of thre rendering

I also update the README and created a specific one for the templates

The PR is ready for a review
