### ISSUE TITLE
Imports for User API outdated for GeoNode v4.3.x

### ISSUE THREAD

**Issue by ridoo** [geosolutions-it/geonode-subsites#40]
It seems that since https://github.com/GeoNode/geonode/issues/12076 the imports do not fit anymore. For example 

https://github.com/geosolutions-it/geonode-subsites/blob/32a65b01a71b2949adbdf7256a0843ea5a27bf0f/subsites/views.py#L4

actually have to import from `people.api.views`.

I kindly offer to review integration into `v4.3.x` and create a dedicated PR if necessary (also including https://github.com/geosolutions-it/geonode-subsites/pull/39)

**Comment by giohappy** [comment]
good point @ridoo.
Feel free to submit a PR, it is very welcomed!

**Comment by ridoo** [comment]
@giohappy there's [already a PR](https://github.com/geosolutions-it/geonode-subsites/pull/41) for review (I have no permission to suggest reviewers).

**Comment by ridoo** [comment]
@giohappy do you want to assign anyone appropriate for review? I do not have any permission on this geosolutions-it space.
